apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-pg-dev
  labels:
    app: trades-pg-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: trades-pg-dev
  template:
    metadata:
      labels:
        project: trades-pg-dev
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-claim
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: trades-pg-dev
  labels:
    env: prod
    owner: me
spec:
  selector:
    project: trades-pg-dev
  ports:
    - name: pg
      protocol: TCP
      port: 5432  # port on load balancer
      targetPort: 5432 # port on pod
  type: LoadBalancer
