apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-front-dev
  labels:
    app: trades-front-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: trades
  template:
    metadata:
      labels:
        project: trades
    spec:
      containers:
        - name: angular-server
          image: trades-front-dev:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4200
