apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-robot-dev
  labels:
    app: trades-robot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: trades-robot-dev
  template:
    metadata:
      labels:
        project: trades-robot-dev
    spec:
      containers:
        - name: rust-robot
          image: robot:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://postgresadmin:admin123@trades-pg-dev.default:5432/postgresdb
---
apiVersion: v1
kind: Service
metadata:
  name: trades-robot-dev
  labels:
    env: prod
    owner: me
spec:
  selector:
    project: trades-robot-dev
  ports:
    - name: rust-robot
      protocol: TCP
      port: 8000 # port on load balancer
      targetPort: 8000 # port on pod
  type: LoadBalancer
