apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-back-dev
  labels:
    app: trades-back-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: trades
  template:
    metadata:
      labels:
        project: trades
    spec:
      containers:
        - name: rust-server
          image: trades-back-dev:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: postgres://postgresadmin:admin123@dev-trades.default:5432/postgresdb
