apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-front-dev
  labels:
    app: trades-front-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: trades-front
  template:
    metadata:
      labels:
        project: trades-front
    spec:
      containers:
        - name: angular-server
          image: trades-front-dev:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: trades-front-dev
  labels:
    env: prod
    owner: me
spec:
  selector:
    project: trades-front
  ports:
    - name: angular-server
      protocol: TCP
      port: 4200 # port on load balancer
      targetPort: 4200 # port on pod
  type: LoadBalancer
