apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-trades
  labels:
    app: dev-trades
spec:
  replicas: 1
  selector:
    matchLabels:
      project: trades
  template:
    metadata:
      labels:
        project: trades
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: dev-trades
  labels:
    env: prod
    owner: me
spec:
  selector:
    project: trades
  ports:
    - name: rust-server
      protocol: TCP
      port: 8080 # port on load balancer
      targetPort: 8080 # port on pod
    - name: angular-server
      protocol: TCP
      port: 4200 # port on load balancer
      targetPort: 4200 # port on pod
    - name: pg
      protocol: TCP
      port: 5432  # port on load balancer
      targetPort: 5432 # port on pod
  type: LoadBalancer
