FROM rust:1.61.0 as build

RUN USER=root cargo new --bin robot
WORKDIR /robot

COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# 3. Build only the dependencies to cache them
RUN cargo build
RUN rm src/*.rs

COPY ./src ./src
RUN rm ./target/debug/deps/robot*
RUN cargo build

COPY ./src ./src

# 5. Build for release.
RUN rm ./target/debug/deps/robot*
RUN cargo install --debug --path .

CMD ["robot"]
